### PR TITLE
Add Nixos flakes building tool

### PR DESCRIPTION
**Pull request by h1sk1**

### CODE REVIEW

**Comment by morganx20** [comment]
垃圾，畜生，诈骗狗，开发你麻痹 死链！
没有用户，没有交易，没应用，没社区，狗杂种！
vsystems is the most shameless and rubbish scam dog in the entire network.
930,000 new vsys scam coins are issued, and only 30 vsys are destroyed every day.
vsys has no applications, no users, and dead chain with no on-chain transactions!

**Comment by morganx20** [comment]
V Systems 是一个闭源死链，它专为诈骗活动而设计。VSYS 每天只处理数百笔交易，并在诈骗狗的操控下不断海量增发。

**Comment by morganx20** [comment]
Xpm&vsys,
垃圾，畜牲，诈骗团伙，都是躲在下水道的老鼠！

**Comment by morganx20** [comment]
畜牲诈骗狗，你们还是人吗？
垃圾！

**Review by sunnyking — APPROVED** [review]

**Pull request merged**
